# Generated by Django 2.2.4 on 2019-08-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190807_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadinternaltwomarks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
