# Generated by Django 2.2.4 on 2019-08-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190804_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetco',
            name='target_co',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
