# Generated by Django 2.2.4 on 2019-08-04 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190804_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='select_co',
            name='CO_for_each_qn',
            field=models.IntegerField(choices=[('CO1', 'CO1'), ('CO2', 'CO2'), ('CO3', 'CO3'), ('CO4', 'CO4'), ('CO5', 'CO5')], validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
