# Generated by Django 2.2.4 on 2019-08-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20190805_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetco',
            name='target_co',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
