# Generated by Django 2.2.4 on 2019-08-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20190804_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='select_co',
            name='CO_for_each_qn',
            field=models.IntegerField(choices=[('1', 'CO1'), ('2', 'CO2'), ('3', 'CO3'), ('4', 'CO4'), ('5', 'CO5')]),
        ),
    ]
