# Generated by Django 2.2.4 on 2019-08-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20190805_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadassignmentmarks',
            name='CO1',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='uploadassignmentmarks',
            name='CO2',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='uploadassignmentmarks',
            name='CO3',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='uploadassignmentmarks',
            name='CO4',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='uploadassignmentmarks',
            name='CO5',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='uploadassignmentmarks',
            name='CO6',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
