# Generated by Django 2.2.4 on 2019-08-05 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20190805_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSemesterMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_num', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=50)),
                ('sem_marks', models.DecimalField(decimal_places=4, max_digits=7)),
                ('no_of_CO', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('marks_for_each_CO', models.IntegerField(validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
