# Generated by Django 2.2.4 on 2019-08-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20190804_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='select_co',
            name='CO_for_each_qn',
            field=models.IntegerField(choices=[('CO1', 'CO1'), ('CO2', 'CO2'), ('CO3', 'CO3'), ('CO4', 'CO4'), ('CO5', 'CO5')], default=1),
        ),
    ]
