# Generated by Django 2.2.4 on 2019-08-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_uploadsemestermarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsemestermarks',
            name='sem_marks',
            field=models.DecimalField(decimal_places=4, max_digits=4),
        ),
    ]
