# Generated by Django 2.2.4 on 2019-08-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20190804_1239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Total_marks',
            new_name='Internal_one_Total_marks',
        ),
    ]
