# Generated by Django 2.2.4 on 2019-08-04 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20190804_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internal_two_Total_marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qn_num', models.IntegerField(validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)])),
                ('marks_for_each_qn', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('CO_for_each_qn', models.IntegerField(choices=[(1, 'CO1'), (2, 'CO2'), (3, 'CO3'), (4, 'CO4'), (5, 'CO5')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Semester_Total_marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qn_num', models.IntegerField(validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)])),
                ('marks_for_each_qn', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('CO_for_each_qn', models.IntegerField(choices=[(1, 'CO1'), (2, 'CO2'), (3, 'CO3'), (4, 'CO4'), (5, 'CO5')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
