# Generated by Django 2.2.4 on 2019-08-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_internal_two_total_marks_semester_total_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internal_one_total_marks',
            name='CO_for_each_qn',
            field=models.IntegerField(choices=[('course_outcome_1', 'CO1'), ('course_outcome_2', 'CO2'), ('course_outcome_3', 'CO3'), ('course_outcome_4', 'CO4'), ('course_outcome_5', 'CO5')], default='course_outcome_1'),
        ),
        migrations.AlterField(
            model_name='internal_two_total_marks',
            name='CO_for_each_qn',
            field=models.IntegerField(choices=[('course_outcome_1', 'CO1'), ('course_outcome_2', 'CO2'), ('course_outcome_3', 'CO3'), ('course_outcome_4', 'CO4'), ('course_outcome_5', 'CO5')], default='course_outcome_1'),
        ),
        migrations.AlterField(
            model_name='semester_total_marks',
            name='CO_for_each_qn',
            field=models.IntegerField(choices=[('course_outcome_1', 'CO1'), ('course_outcome_2', 'CO2'), ('course_outcome_3', 'CO3'), ('course_outcome_4', 'CO4'), ('course_outcome_5', 'CO5')], default='course_outcome_1'),
        ),
    ]
