# Generated by Django 2.2.4 on 2019-08-04 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20190804_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_num', models.IntegerField(choices=[(1, 'CO1'), (2, 'CO2'), (3, 'CO3'), (4, 'CO4'), (5, 'CO5')], default=1)),
                ('total_marks_for_co', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.AlterField(
            model_name='internal_one_total_marks',
            name='CO_for_each_qn',
            field=models.IntegerField(choices=[(1, 'CO1'), (2, 'CO2'), (3, 'CO3'), (4, 'CO4'), (5, 'CO5')], default=1),
        ),
        migrations.AlterField(
            model_name='internal_two_total_marks',
            name='CO_for_each_qn',
            field=models.IntegerField(choices=[(1, 'CO1'), (2, 'CO2'), (3, 'CO3'), (4, 'CO4'), (5, 'CO5')], default=1),
        ),
        migrations.AlterField(
            model_name='semester_total_marks',
            name='CO_for_each_qn',
            field=models.IntegerField(choices=[(1, 'CO1'), (2, 'CO2'), (3, 'CO3'), (4, 'CO4'), (5, 'CO5')], default=1),
        ),
    ]
